spring.application.name=task-manager
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate

# Keep hikari small when using Neon Pooler
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1


jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# SMTP2GO Mail
spring.mail.host=mail.smtp2go.com
spring.mail.port=587
spring.mail.username=${SMTP2GO_USERNAME}
spring.mail.password=${SMTP2GO_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=${MAIL_FROM}
app.frontend.url=${FRONTEND_URL}
